#!/bin/bash
#a=$(sensors | grep -i 'curr' | head -n1)
#b=$(sensors | grep -i 'curr' | tail -n1)
#echo "CHARGER CURRENT:"
#echo $a
#echo "BAT CURRENT:"
#echo $b

bat=$(findbat)
if [ $? != 0 ] || [ "$bat" = "" ]; then
	echo "Failed to find the battery!" >&2
	echo "Please look for any errors above.  Likely \`findbat' just isn't installed." >&2
	exit 1
fi

percent=$(cat $bat/capacity)
if [ $percent -lt 35 ]; then
	pre="\033[1;31m!!! "
	post=" !!! \033[0m"
elif [ $percent -lt 45 ]; then
	pre="\033[31m"
	post="\033[0m"
elif [ $percent -lt 65 ]; then
	pre="\033[1;33m"
	post="\033[0m"
elif [ $percent -lt 75 ]; then
	pre="\033[1;32m"
	post="\033[0m"
elif [ $percent -gt 75 ]; then
	pre="\033[32m"
	post="\033[0m"
fi
echo -e "BAT PERCENT: ${pre}${percent}${post}"
status=$(cat $bat/status)
if [ "$status" = "Charging" ]; then
	pre="\033[32m"
elif [ "$status" = "Discharging" ]; then
	pre="\033[1;31m"
else
	pre="\033[1;33m"
fi

current=$(cat $bat/current_now)
if [ $current -lt 1000000 ] && [ $current -gt 0 ]; then
	pre="\033[1;33mSlow "
fi
echo -e "BAT STATUS : ${pre}${status}\033[0m"
