#!/bin/sh
for bat in /sys/class/power_supply/*; do
	ls $bat/capacity > /dev/null 2>&1
	if [ $? = 0 ]; then
		# we found one with capacity
		echo "$bat"
		exit 0
	fi
done
echo "ERROR: No battery found!!!" 1>&2
exit 1
